### ISSUE TITLE
Web Portal Login page error after entering credentials

### ISSUE THREAD

**Issue by plam626** [CovidShield/portal#75]
After entering username and password not found in db, Web Portal Login shows error "We're sorry, but something went wrong" message.

OS: MacOS Catalina 10.15.5

Steps:
1. Clone Portal repo, build and run through Docker
2. Open browser and go to http://localhost:3000/login
3. Enter the following credentials:
U: admin@covidshield.app
P: password

Expected Result:
3. If credentials correct, login successfully
3. If credentials incorrect, message shows incorrect user/password

Actual Result:
3. Error "We're sorry, but something went wrong" message.

Portal Log:
I, [2020-05-29T16:42:34.873562 #100] INFO -- : [1d61c360-0b6b-47dd-a1c8-bae406fd4041] Parameters: {"authenticity_token"=>"HoDxfgdRotHcbqQuGVZXu9bIpM3RFjN+iBjGZO+JtTmF4Y5MlodsAjhtxJWYFrf4niK1KRE1zlWAHmFlWQrJzg==", "username"=>"admin@covidshield.app", "password"=>"[FILTERED]", "commit"=>"Sign in"}
I, [2020-05-29T16:42:34.879902 #100] INFO -- : [1d61c360-0b6b-47dd-a1c8-bae406fd4041] Completed 500 Internal Server Error in 6ms (ActiveRecord: 4.2ms | Allocations: 474)
F, [2020-05-29T16:42:34.881707 #100] FATAL -- : [1d61c360-0b6b-47dd-a1c8-bae406fd4041]
[1d61c360-0b6b-47dd-a1c8-bae406fd4041] ActiveRecord::StatementInvalid (Mysql2::Error: Table 'portal.users' doesn't exist):
[1d61c360-0b6b-47dd-a1c8-bae406fd4041]
[1d61c360-0b6b-47dd-a1c8-bae406fd4041] app/controllers/sessions_controller.rb:9:in `create'
[1d61c360-0b6b-47dd-a1c8-bae406fd4041] app/controllers/application_controller.rb:32:in `switch_locale'
 
<img width="653" alt="Screen Shot 2020-05-29 at 12 41 38 PM" src="https://user-images.githubusercontent.com/5530175/83286074-58d52800-a1ad-11ea-8141-2f5443f4f40d.png">

**Comment by plam626** [comment]
Figured out issue... need to run ./bootstrap.sh first. Thanks!
